-- ============================================================
-- RUTEX - Ciudades de la tienda
-- Ejecutar en Supabase SQL Editor (idempotente)
-- Lista simple de ciudades para envíos/entregas. El id es
-- autoincremental (identity) y empieza en 1.
-- ============================================================

create table if not exists public.cities (
  id         int generated by default as identity primary key,
  name       text not null,
  created_at timestamptz not null default now()
);

-- No permitir duplicados (insensible a mayúsculas/minúsculas)
create unique index if not exists ux_cities_name on public.cities (lower(name));

alter table public.cities enable row level security;

-- Lectura para autenticados; escritura solo administradores
create policy "cities_select" on public.cities
  for select using (auth.uid() is not null);
create policy "cities_insert" on public.cities
  for insert with check (public.is_admin());
create policy "cities_update" on public.cities
  for update using (public.is_admin());
create policy "cities_delete" on public.cities
  for delete using (public.is_admin());