-- ============================================================
-- RUTEX - Mermas (bajas de stock por producto)
-- Ejecutar en Supabase SQL Editor (idempotente)
--
-- Modelo: al crear una merma se registra la cantidad que se da de
-- baja a cada producto (empieza en 0, el usuario suma/resta).
-- Al guardar, el stock del producto DISMINUYE según lo ingresado.
-- Al editar, el stock se ajusta por la diferencia (anterior - nueva).
-- Al eliminar, el stock vuelve a sumarse (se revierte lo restado).
-- Los items se guardan en un JSON con el nombre del producto, la
-- cantidad restada y el valor de compra y venta vigentes:
--   [{ productId, productName, quantity, purchasePrice, sellPrice }]
-- Número de merma: MER[YYYYMMDD][6 dígitos] => MER20260908000001
-- ============================================================

-- ---------- MOTIVOS DE MERMA (catálogo) ----------
create table if not exists public.merma_motivos (
  id         int  generated by default as identity primary key,
  name       text not null unique,
  created_at timestamptz not null default now()
);

-- Semilla con los motivos genéricos más comunes (no reintroduce duplicados).
insert into public.merma_motivos (name)
select unnest(array[
  'Caducado o vencido',
  'Dañado o roto',
  'Devolución en mal estado',
  'Robo o pérdida',
  'Error de conteo / inventario',
  'Merma por manipulación',
  'Exhibición o muestra',
  'Consumo interno',
  'Producto obsoleto o descontinuado',
  'Fuga, derrame o contaminación',
  'Rechazo de control de calidad',
  'Descomposición o deterioro'
])
on conflict (name) do nothing;

-- ---------- CONTADOR DIARIO ----------
create table if not exists public.merma_counters (
  day         date primary key,
  last_number int not null default 0 check (last_number between 0 and 999999)
);

-- ---------- FUNCIÓN ATOMICA (siguiente número de merma) ----------
create or replace function public.next_merma_number()
returns text
language sql
security definer
set search_path = public
as $$
  insert into public.merma_counters (day, last_number)
  values (current_date, 1)
  on conflict (day) do update
    set last_number = public.merma_counters.last_number + 1
  returning 'MER' || to_char(day, 'YYYYMMDD') || lpad(last_number::text, 6, '0');
$$;

grant execute on function public.next_merma_number() to anon, authenticated, service_role;

-- ---------- TABLA DE MERMAS ----------
create table if not exists public.mermas (
  id           uuid primary key default gen_random_uuid(),
  merma_number text not null,
  motivo_id    int  not null references public.merma_motivos(id),
  items        jsonb not null default '[]'::jsonb,
  total_value  numeric not null default 0,
  observation  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);

create unique index if not exists ux_mermas_number on public.mermas (merma_number);
create index if not exists ix_mermas_created on public.mermas (created_at);
create index if not exists ix_mermas_motivo on public.mermas (motivo_id);

-- ---------- SEMILLA: arrancar el contador de hoy donde quedó el último ----------
insert into public.merma_counters (day, last_number)
select current_date, coalesce(max((regexp_match(merma_number, '^MER[0-9]{8}([0-9]{6})$'))[1]::int), 0)
from public.mermas
where merma_number ~ '^MER[0-9]{8}[0-9]{6}$'
on conflict (day) do nothing;

-- ---------- ROW LEVEL SECURITY ----------
alter table public.mermas enable row level security;

-- Lectura para autenticados; escritura y borrado solo administradores.
create policy "mermas_select" on public.mermas
  for select using (auth.uid() is not null);
create policy "mermas_insert" on public.mermas
  for insert with check (public.is_admin());
create policy "mermas_update" on public.mermas
  for update using (public.is_admin());
create policy "mermas_delete" on public.mermas
  for delete using (public.is_admin());

-- ---------- RLS MOTIVOS ----------
alter table public.merma_motivos enable row level security;

create policy "merma_motivos_select" on public.merma_motivos
  for select using (auth.uid() is not null);
create policy "merma_motivos_insert" on public.merma_motivos
  for insert with check (public.is_admin());
create policy "merma_motivos_update" on public.merma_motivos
  for update using (public.is_admin());
create policy "merma_motivos_delete" on public.merma_motivos
  for delete using (public.is_admin());